M48
; DRILL file {KiCad 7.0.7-7.0.7~ubuntu22.04.1} date za 07 okt 2023 11:06:41 CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-07T11:06:41+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7-7.0.7~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.520
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X124.0Y-128.25
T2
X153.15Y-110.4
X153.15Y-113.4
T1
G00X124.0Y-120.85
M15
G01X124.0Y-120.65
M16
G05
T0
M30
